/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedEintraegeRouteImport } from './routes/_authenticated/eintraege'
import { Route as AuthenticatedFreieTermineRouteImport } from './routes/_authenticated/freie-termine'
import { Route as AuthenticatedMigrationRouteImport } from './routes/_authenticated/migration'
import { Route as ApiPublicWebhooksResendRouteImport } from './routes/api/public/webhooks/resend'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEintraegeRoute = AuthenticatedEintraegeRouteImport.update({
  id: '/eintraege',
  path: '/eintraege',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFreieTermineRoute =
  AuthenticatedFreieTermineRouteImport.update({
    id: '/freie-termine',
    path: '/freie-termine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMigrationRoute = AuthenticatedMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksResendRoute = ApiPublicWebhooksResendRouteImport.update({
  id: '/api/public/webhooks/resend',
  path: '/api/public/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/eintraege': typeof AuthenticatedEintraegeRoute
  '/freie-termine': typeof AuthenticatedFreieTermineRoute
  '/migration': typeof AuthenticatedMigrationRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/eintraege': typeof AuthenticatedEintraegeRoute
  '/freie-termine': typeof AuthenticatedFreieTermineRoute
  '/migration': typeof AuthenticatedMigrationRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/eintraege': typeof AuthenticatedEintraegeRoute
  '/_authenticated/freie-termine': typeof AuthenticatedFreieTermineRoute
  '/_authenticated/migration': typeof AuthenticatedMigrationRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/einstellungen'
    | '/eintraege'
    | '/freie-termine'
    | '/migration'
    | '/api/public/webhooks/resend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/einstellungen'
    | '/eintraege'
    | '/freie-termine'
    | '/migration'
    | '/'
    | '/api/public/webhooks/resend'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/einstellungen'
    | '/_authenticated/eintraege'
    | '/_authenticated/freie-termine'
    | '/_authenticated/migration'
    | '/_authenticated/'
    | '/api/public/webhooks/resend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksResendRoute: typeof ApiPublicWebhooksResendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eintraege': {
      id: '/_authenticated/eintraege'
      path: '/eintraege'
      fullPath: '/eintraege'
      preLoaderRoute: typeof AuthenticatedEintraegeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freie-termine': {
      id: '/_authenticated/freie-termine'
      path: '/freie-termine'
      fullPath: '/freie-termine'
      preLoaderRoute: typeof AuthenticatedFreieTermineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/migration': {
      id: '/_authenticated/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof AuthenticatedMigrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/resend': {
      id: '/api/public/webhooks/resend'
      path: '/api/public/webhooks/resend'
      fullPath: '/api/public/webhooks/resend'
      preLoaderRoute: typeof ApiPublicWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedEintraegeRoute: typeof AuthenticatedEintraegeRoute
  AuthenticatedFreieTermineRoute: typeof AuthenticatedFreieTermineRoute
  AuthenticatedMigrationRoute: typeof AuthenticatedMigrationRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedEintraegeRoute: AuthenticatedEintraegeRoute,
  AuthenticatedFreieTermineRoute: AuthenticatedFreieTermineRoute,
  AuthenticatedMigrationRoute: AuthenticatedMigrationRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksResendRoute: ApiPublicWebhooksResendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
