/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedEintraegeRouteImport } from './routes/_authenticated/eintraege'
import { Route as AuthenticatedFreieTermineRouteImport } from './routes/_authenticated/freie-termine'
import { Route as AuthenticatedMigrationRouteImport } from './routes/_authenticated/migration'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as ApiPublicResendConfigCheckRouteImport } from './routes/api/public/resend-config-check'
import { Route as ApiPublicBackupsRunRouteImport } from './routes/api/public/backups/run'
import { Route as ApiPublicRadarSyncRouteImport } from './routes/api/public/radar/sync'
import { Route as ApiPublicWebhooksResendRouteImport } from './routes/api/public/webhooks/resend'
import { Route as ApiPublicIntegrationsKundicalcV1EventsRouteImport } from './routes/api/public/integrations/kundicalc/v1/events'
import { Route as ApiPublicIntegrationsKundicalcV1HandoverRouteImport } from './routes/api/public/integrations/kundicalc/v1/handover'
import { Route as ApiPublicIntegrationsKundicalcV1MasterDataRouteImport } from './routes/api/public/integrations/kundicalc/v1/master-data'
import { Route as ApiPublicIntegrationsKundicalcV1EventsEventIdRouteImport } from './routes/api/public/integrations/kundicalc/v1/events/$eventId'
import { Route as ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRouteImport } from './routes/api/public/integrations/kundicalc/v1/receipts/$sourceEventId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEintraegeRoute = AuthenticatedEintraegeRouteImport.update({
  id: '/eintraege',
  path: '/eintraege',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFreieTermineRoute =
  AuthenticatedFreieTermineRouteImport.update({
    id: '/freie-termine',
    path: '/freie-termine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMigrationRoute = AuthenticatedMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicResendConfigCheckRoute =
  ApiPublicResendConfigCheckRouteImport.update({
    id: '/api/public/resend-config-check',
    path: '/api/public/resend-config-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBackupsRunRoute = ApiPublicBackupsRunRouteImport.update({
  id: '/api/public/backups/run',
  path: '/api/public/backups/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadarSyncRoute = ApiPublicRadarSyncRouteImport.update({
  id: '/api/public/radar/sync',
  path: '/api/public/radar/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksResendRoute = ApiPublicWebhooksResendRouteImport.update({
  id: '/api/public/webhooks/resend',
  path: '/api/public/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntegrationsKundicalcV1EventsRoute =
  ApiPublicIntegrationsKundicalcV1EventsRouteImport.update({
    id: '/api/public/integrations/kundicalc/v1/events',
    path: '/api/public/integrations/kundicalc/v1/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsKundicalcV1HandoverRoute =
  ApiPublicIntegrationsKundicalcV1HandoverRouteImport.update({
    id: '/api/public/integrations/kundicalc/v1/handover',
    path: '/api/public/integrations/kundicalc/v1/handover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsKundicalcV1MasterDataRoute =
  ApiPublicIntegrationsKundicalcV1MasterDataRouteImport.update({
    id: '/api/public/integrations/kundicalc/v1/master-data',
    path: '/api/public/integrations/kundicalc/v1/master-data',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsKundicalcV1EventsEventIdRoute =
  ApiPublicIntegrationsKundicalcV1EventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => ApiPublicIntegrationsKundicalcV1EventsRoute,
  } as any)
const ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRoute =
  ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRouteImport.update({
    id: '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId',
    path: '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/eintraege': typeof AuthenticatedEintraegeRoute
  '/freie-termine': typeof AuthenticatedFreieTermineRoute
  '/migration': typeof AuthenticatedMigrationRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/api/public/resend-config-check': typeof ApiPublicResendConfigCheckRoute
  '/api/public/backups/run': typeof ApiPublicBackupsRunRoute
  '/api/public/radar/sync': typeof ApiPublicRadarSyncRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/api/public/integrations/kundicalc/v1/events': typeof ApiPublicIntegrationsKundicalcV1EventsRouteWithChildren
  '/api/public/integrations/kundicalc/v1/handover': typeof ApiPublicIntegrationsKundicalcV1HandoverRoute
  '/api/public/integrations/kundicalc/v1/master-data': typeof ApiPublicIntegrationsKundicalcV1MasterDataRoute
  '/api/public/integrations/kundicalc/v1/events/$eventId': typeof ApiPublicIntegrationsKundicalcV1EventsEventIdRoute
  '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId': typeof ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/eintraege': typeof AuthenticatedEintraegeRoute
  '/freie-termine': typeof AuthenticatedFreieTermineRoute
  '/migration': typeof AuthenticatedMigrationRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/resend-config-check': typeof ApiPublicResendConfigCheckRoute
  '/api/public/backups/run': typeof ApiPublicBackupsRunRoute
  '/api/public/radar/sync': typeof ApiPublicRadarSyncRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/api/public/integrations/kundicalc/v1/events': typeof ApiPublicIntegrationsKundicalcV1EventsRouteWithChildren
  '/api/public/integrations/kundicalc/v1/handover': typeof ApiPublicIntegrationsKundicalcV1HandoverRoute
  '/api/public/integrations/kundicalc/v1/master-data': typeof ApiPublicIntegrationsKundicalcV1MasterDataRoute
  '/api/public/integrations/kundicalc/v1/events/$eventId': typeof ApiPublicIntegrationsKundicalcV1EventsEventIdRoute
  '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId': typeof ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/eintraege': typeof AuthenticatedEintraegeRoute
  '/_authenticated/freie-termine': typeof AuthenticatedFreieTermineRoute
  '/_authenticated/migration': typeof AuthenticatedMigrationRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/resend-config-check': typeof ApiPublicResendConfigCheckRoute
  '/api/public/backups/run': typeof ApiPublicBackupsRunRoute
  '/api/public/radar/sync': typeof ApiPublicRadarSyncRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/api/public/integrations/kundicalc/v1/events': typeof ApiPublicIntegrationsKundicalcV1EventsRouteWithChildren
  '/api/public/integrations/kundicalc/v1/handover': typeof ApiPublicIntegrationsKundicalcV1HandoverRoute
  '/api/public/integrations/kundicalc/v1/master-data': typeof ApiPublicIntegrationsKundicalcV1MasterDataRoute
  '/api/public/integrations/kundicalc/v1/events/$eventId': typeof ApiPublicIntegrationsKundicalcV1EventsEventIdRoute
  '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId': typeof ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/einstellungen'
    | '/eintraege'
    | '/freie-termine'
    | '/migration'
    | '/radar'
    | '/api/public/resend-config-check'
    | '/api/public/backups/run'
    | '/api/public/radar/sync'
    | '/api/public/webhooks/resend'
    | '/api/public/integrations/kundicalc/v1/events'
    | '/api/public/integrations/kundicalc/v1/handover'
    | '/api/public/integrations/kundicalc/v1/master-data'
    | '/api/public/integrations/kundicalc/v1/events/$eventId'
    | '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/einstellungen'
    | '/eintraege'
    | '/freie-termine'
    | '/migration'
    | '/radar'
    | '/'
    | '/api/public/resend-config-check'
    | '/api/public/backups/run'
    | '/api/public/radar/sync'
    | '/api/public/webhooks/resend'
    | '/api/public/integrations/kundicalc/v1/events'
    | '/api/public/integrations/kundicalc/v1/handover'
    | '/api/public/integrations/kundicalc/v1/master-data'
    | '/api/public/integrations/kundicalc/v1/events/$eventId'
    | '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/einstellungen'
    | '/_authenticated/eintraege'
    | '/_authenticated/freie-termine'
    | '/_authenticated/migration'
    | '/_authenticated/radar'
    | '/_authenticated/'
    | '/api/public/resend-config-check'
    | '/api/public/backups/run'
    | '/api/public/radar/sync'
    | '/api/public/webhooks/resend'
    | '/api/public/integrations/kundicalc/v1/events'
    | '/api/public/integrations/kundicalc/v1/handover'
    | '/api/public/integrations/kundicalc/v1/master-data'
    | '/api/public/integrations/kundicalc/v1/events/$eventId'
    | '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicResendConfigCheckRoute: typeof ApiPublicResendConfigCheckRoute
  ApiPublicBackupsRunRoute: typeof ApiPublicBackupsRunRoute
  ApiPublicRadarSyncRoute: typeof ApiPublicRadarSyncRoute
  ApiPublicWebhooksResendRoute: typeof ApiPublicWebhooksResendRoute
  ApiPublicIntegrationsKundicalcV1EventsRoute: typeof ApiPublicIntegrationsKundicalcV1EventsRouteWithChildren
  ApiPublicIntegrationsKundicalcV1HandoverRoute: typeof ApiPublicIntegrationsKundicalcV1HandoverRoute
  ApiPublicIntegrationsKundicalcV1MasterDataRoute: typeof ApiPublicIntegrationsKundicalcV1MasterDataRoute
  ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRoute: typeof ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eintraege': {
      id: '/_authenticated/eintraege'
      path: '/eintraege'
      fullPath: '/eintraege'
      preLoaderRoute: typeof AuthenticatedEintraegeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freie-termine': {
      id: '/_authenticated/freie-termine'
      path: '/freie-termine'
      fullPath: '/freie-termine'
      preLoaderRoute: typeof AuthenticatedFreieTermineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/migration': {
      id: '/_authenticated/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof AuthenticatedMigrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/resend-config-check': {
      id: '/api/public/resend-config-check'
      path: '/api/public/resend-config-check'
      fullPath: '/api/public/resend-config-check'
      preLoaderRoute: typeof ApiPublicResendConfigCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backups/run': {
      id: '/api/public/backups/run'
      path: '/api/public/backups/run'
      fullPath: '/api/public/backups/run'
      preLoaderRoute: typeof ApiPublicBackupsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar/sync': {
      id: '/api/public/radar/sync'
      path: '/api/public/radar/sync'
      fullPath: '/api/public/radar/sync'
      preLoaderRoute: typeof ApiPublicRadarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/resend': {
      id: '/api/public/webhooks/resend'
      path: '/api/public/webhooks/resend'
      fullPath: '/api/public/webhooks/resend'
      preLoaderRoute: typeof ApiPublicWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/kundicalc/v1/events': {
      id: '/api/public/integrations/kundicalc/v1/events'
      path: '/api/public/integrations/kundicalc/v1/events'
      fullPath: '/api/public/integrations/kundicalc/v1/events'
      preLoaderRoute: typeof ApiPublicIntegrationsKundicalcV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/kundicalc/v1/handover': {
      id: '/api/public/integrations/kundicalc/v1/handover'
      path: '/api/public/integrations/kundicalc/v1/handover'
      fullPath: '/api/public/integrations/kundicalc/v1/handover'
      preLoaderRoute: typeof ApiPublicIntegrationsKundicalcV1HandoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/kundicalc/v1/master-data': {
      id: '/api/public/integrations/kundicalc/v1/master-data'
      path: '/api/public/integrations/kundicalc/v1/master-data'
      fullPath: '/api/public/integrations/kundicalc/v1/master-data'
      preLoaderRoute: typeof ApiPublicIntegrationsKundicalcV1MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/kundicalc/v1/events/$eventId': {
      id: '/api/public/integrations/kundicalc/v1/events/$eventId'
      path: '/$eventId'
      fullPath: '/api/public/integrations/kundicalc/v1/events/$eventId'
      preLoaderRoute: typeof ApiPublicIntegrationsKundicalcV1EventsEventIdRouteImport
      parentRoute: typeof ApiPublicIntegrationsKundicalcV1EventsRoute
    }
    '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId': {
      id: '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId'
      path: '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId'
      fullPath: '/api/public/integrations/kundicalc/v1/receipts/$sourceEventId'
      preLoaderRoute: typeof ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedEintraegeRoute: typeof AuthenticatedEintraegeRoute
  AuthenticatedFreieTermineRoute: typeof AuthenticatedFreieTermineRoute
  AuthenticatedMigrationRoute: typeof AuthenticatedMigrationRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedEintraegeRoute: AuthenticatedEintraegeRoute,
  AuthenticatedFreieTermineRoute: AuthenticatedFreieTermineRoute,
  AuthenticatedMigrationRoute: AuthenticatedMigrationRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicIntegrationsKundicalcV1EventsRouteChildren {
  ApiPublicIntegrationsKundicalcV1EventsEventIdRoute: typeof ApiPublicIntegrationsKundicalcV1EventsEventIdRoute
}

const ApiPublicIntegrationsKundicalcV1EventsRouteChildren: ApiPublicIntegrationsKundicalcV1EventsRouteChildren =
  {
    ApiPublicIntegrationsKundicalcV1EventsEventIdRoute:
      ApiPublicIntegrationsKundicalcV1EventsEventIdRoute,
  }

const ApiPublicIntegrationsKundicalcV1EventsRouteWithChildren =
  ApiPublicIntegrationsKundicalcV1EventsRoute._addFileChildren(
    ApiPublicIntegrationsKundicalcV1EventsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicResendConfigCheckRoute: ApiPublicResendConfigCheckRoute,
  ApiPublicBackupsRunRoute: ApiPublicBackupsRunRoute,
  ApiPublicRadarSyncRoute: ApiPublicRadarSyncRoute,
  ApiPublicWebhooksResendRoute: ApiPublicWebhooksResendRoute,
  ApiPublicIntegrationsKundicalcV1EventsRoute:
    ApiPublicIntegrationsKundicalcV1EventsRouteWithChildren,
  ApiPublicIntegrationsKundicalcV1HandoverRoute:
    ApiPublicIntegrationsKundicalcV1HandoverRoute,
  ApiPublicIntegrationsKundicalcV1MasterDataRoute:
    ApiPublicIntegrationsKundicalcV1MasterDataRoute,
  ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRoute:
    ApiPublicIntegrationsKundicalcV1ReceiptsSourceEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
